require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.luasnips")
require("user.diagnostics")
require("user.autocmds")
require("user.telescope")
require("user.treesitter")
require("user.nvim-tree")
require("user.blink")

require("user.toogle_term")
