require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.luasnips")
-- TODO: remove what is not necessary anymore
-- require("user.cmp")
-- require("user.lsp")
require("user.diagnostics")
require("user.autocmds")
require("user.telescope")
require("user.treesitter")
require("user.nvim-tree")
require("user.blink")

require("user.toogle_term")
